#---
## handlers file for aws-web
#
#- name: Run the equivalent of "apt-get update" as a separate step. Thanks, bugs
#- apt: name=aptitude state=present
#- apt: update_cache=yes upgrade=safe cache_valid_time=3600
#  sudo: yes
#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist
#  sudo: yes


- name: upgrade all packages
  apt:
    name: '*'
    state: latest